[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
fs_permissions = [{ access = "read", path = "./test"}]
#auto_detect_solc = true

[rpc_endpoints]
ftm-testnet = "${FTM_TESTNET_RPC}"

[etherscan]
[etherscan.ftm-testnet]
url = "https://testnet.ftmscan.com"
key = "${FTMSCAN_API_KEY}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
