[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
ftm-testnet = "${FTM_TESTNET_RPC}"

[etherscan]
[etherscan.ftm-testnet]
url = "https://testnet.ftmscan.com"
key = "${FTMSCAN_API_KEY}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
